name: create-pr-preview

on: [pull_request]

jobs:
  create-update:
    permissions:
      discussions: write
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get commit message
        id: get_commit_message
        run: echo "message=$(git show -s --format=%s)" >> "$GITHUB_OUTPUT"

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install dependencies
        run: bun install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # `github.event.pull_request.head.ref` is only available on `pull_request` triggers.
          # Use your own, or keep the automatically inferred branch name from `--auto`, when using different triggers.
          command: eas update --auto --branch ${{ github.event.pull_request.head.ref }} --message "${{ steps.get_commit_message.outputs.message }}"
