name: publish-app-update

on:
  push:
    branches:
      - development
      - preview
      - production

jobs:
  create-eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup EAS
        uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install dependencies
        run: bun install

      - name: Create update
        run: eas update --auto --non-interactive

  create-build:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Expo GitHub Action
        uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install dependencies
        run: bun install

      - name: Create build
        run: eas build --platform=android --non-interactive

  create-release:
    # needs: [create-build]
    # if: needs.create-build.result == 'success'

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Expo GitHub Action
        uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install expo
        run: bun i expo

      - name: Set environment variables
        run: |
          eas build:list --limit=1 --build-profile=production --json --non-interactive
          echo "ARTIFACT_URL=$( eas build:list --limit=1 --build-profile=production --json --non-interactive \
            | jq -r ".[0].artifacts.applicationArchiveUrl" )" >> $GITHUB_ENV
          echo "APP_VERSION=$( eas build:list --limit=1 --build-profile=production --json --non-interactive \
            | jq -r ".[0].appVersion" )" >> $GITHUB_ENV
          echo "COMMIT_MESSAGE=$( eas build:list --limit=1 --build-profile=production --json --non-interactive \
            | jq -r ".[0].gitCommitMessage" )" >> $GITHUB_ENV

      - name: Get build artifact
        run: curl -L -o caiet-de-cantari-v"$APP_VERSION".apk "$ARTIFACT_URL"

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          gh release create \
            "v$APP_VERSION" \
            caiet-de-cantari-v"$APP_VERSION" \
            --latest \
            --target "production" \
            --title "v$APP_VERSION" \
            --notes-from-tag \
            --notes-from-tag

