name: publish-app-update

on:
  push:
    branches:
      - development
      - preview
      - production

jobs:
  create-eas-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Expo GitHub Action
        uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install dependencies
        run: bun install

      - name: Create update
        run: eas update --auto --non-interactive

  create-build:
    if: github.ref == 'refs/heads/production'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Expo GitHub Action
        uses: expo/expo-github-action@8.2.1
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install dependencies
        run: bun install

      - name: Create build
        run: eas build --non-interactive
