name: update-expo-sdk

on:
  push:
    branches:
      - wip-update-expo-weekly-action
  schedule:
    - cron: "0 8 * * MON"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup expo-cli
        uses: expo/expo-github-action@8.2.1
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
          packager: bun

      - name: Install packages
        run: bun install

      - name: Update expo
        run: bun expo install expo@latest

      - name: Fix dependencies
        run: bun expo install --fix

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create temp branch and commit changes
        run: |
          echo "BRANCH=expo-sdk-update-$(date +%d-%m-%Y)" >> $GITHUB_ENV
          git checkout -b "$BRANCH"
          git add .
          git commit -m "chore: weekly expo sdk update"
          git push origin "$BRANCH"
          # echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Create pull request
        env:
          GH_TOKEN: ${{ secrets.GH_CREATE_PR_TOKEN }}
        run: |
          gh auth setup-git
          gh pr create \
            --title "weekly expo sdk update" \
            --body "update expo sdk to the latest version along with its dependencies" \
            --head "$BRANCH" \
            --base development
